# Generated by Django 3.2 on 2022-09-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregisterationrequests',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
