# Generated by Django 3.2 on 2022-09-25 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ActivityEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=30)),
                ('activity_description', models.CharField(blank=True, max_length=1024)),
                ('points', models.IntegerField()),
                ('evidence_needed', models.CharField(max_length=1024)),
                ('end_date', models.DateTimeField(null=True)),
                ('edited', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('original_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCategoryEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('description', models.CharField(default='', max_length=255)),
                ('end_date', models.DateTimeField(null=True)),
                ('budget', models.IntegerField()),
                ('edited', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('original_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activitycategory')),
            ],
        ),
    ]
