# Generated by Django 3.2 on 2022-09-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20220925_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityedit',
            name='evidence_needed',
        ),
    ]
