# Generated by Django 3.2 on 2022-09-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activityedit_evidence_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
